[package]
name = "line-server-exercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.3.1", features = ["derive"] }
log = "0.4"
env_logger = "0.10.0"
